// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Name        string `json:"name"`
	AccessToken string `json:"access_token"`
}

type PartyReq struct {
	PartyName string `json:"party_name"`
	PartyId   string `json:"party_id"`
}

type PartyResp struct {
	PartyName string `json:"party_name"`
	PartyId   string `json:"party_id"`
}

type JwtTokenResponse struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
}
